# [START django_app]
runtime: python37


handlers:
- url: /static
  static_dir: static/
- url: .*
  script: web2019_12_1.wsgi.application

# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK 
# Using Third Party Libraries: https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27
# [END django_app]

